name: Deploy to Google Cloud Functions and Set Up Scheduler

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  FUNCTION_NAME: select_topic_and_send_email
  REGION: europe-west2
  TOPIC_NAME: daily-topic
  SCHEDULER_JOB_NAME: daily-topic-job

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy Cloud Function
      run: |
        gcloud functions deploy ${{ env.FUNCTION_NAME }} \
          --runtime python39 \
          --trigger-topic ${{ env.TOPIC_NAME }} \
          --set-env-vars SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }} \
          --region=${{ env.REGION }}

    - name: Set up Cloud Scheduler
      run: |
        # Check if the scheduler job already exists
        if gcloud scheduler jobs describe ${{ env.SCHEDULER_JOB_NAME }} --location=${{ env.REGION }}; then
          # Update existing job
          gcloud scheduler jobs update pubsub ${{ env.SCHEDULER_JOB_NAME }} \
            --schedule "0 8 * * *" \
            --topic ${{ env.TOPIC_NAME }} \
            --message-body "It's time for daily topic!" \
            --location=${{ env.REGION }}
        else
          # Create new job
          gcloud scheduler jobs create pubsub ${{ env.SCHEDULER_JOB_NAME }} \
            --schedule "0 8 * * *" \
            --topic ${{ env.TOPIC_NAME }} \
            --message-body "It's time for daily topic!" \
            --location=${{ env.REGION }}
        fi

    - name: Debug Information
      run: |
        echo "Function Name: ${{ env.FUNCTION_NAME }}"
        echo "Region: ${{ env.REGION }}"
        echo "Topic Name: ${{ env.TOPIC_NAME }}"
        echo "Scheduler Job Name: ${{ env.SCHEDULER_JOB_NAME }}"